version: '3.7'

networks:
    frontend:
        driver: external

services:
    app:
        build: ./
        command: streamlit run app/main.py --server.port 8501
        volumes:
            - ./:/app
        ports:
            - 8501:8501
        image: employmentServicesDashboard:latest
        networks:
            - frontend
